BoudlGroup/Areas/ar/Controllers/FindAHotelController.cs
using Boudl.Client.Mvc;
using BoudlGroup.Header;
using BoudlGroup.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace BoudlGroup.Areas.ar.Controllers
{
    public class FindAHotelController : Controller
    {
        // GET: ar/FindAHotel
        //public ActionResult Index()
        //{
        //    return View();
        //}
        public static Int64 HtId = 0;
        public static string FixedAmenitiesIds = "";
        public static string FixedBrandIds = "";

        public async Task<ActionResult> Index()
        {
            FindAHotelDTO obja = new FindAHotelDTO();
            using (HttpClient client = new HttpClient())
            {
                CommonHeader.setHeaders(client);
                ManageHotelAmenitiesDTO aObj = new ManageHotelAmenitiesDTO();
                FindAHotelNewDTO obj = new FindAHotelNewDTO();
                List<ManageCountriesDTO> CountriesList = new List<ManageCountriesDTO>();
                List<ManageCitiesDTO> Cityist = new List<ManageCitiesDTO>();
                //List<ManageBranchesDTO> BranchList = new List<ManageBranchesDTO>();
                string y = null;
                if (TempData["htlId"] != null)
                    ViewData["HotelId"] = TempData["htlId"];
                if (TempData["AmtId"] != null)
                    ViewData["AmenityId"] = TempData["AmtId"];
                List<ManageHotelAmenitiesDTO> a = new List<ManageHotelAmenitiesDTO>();
                ManageCountriesDTO CountryObj = new ManageCountriesDTO();
                ManageCitiesDTO cityObj = new ManageCitiesDTO();
                List<ManageCountriesDTO> CountryList = new List<ManageCountriesDTO>();
                List<ManageCitiesDTO> CityList = new List<ManageCitiesDTO>();
                List<ManageBranchesDTO> BranchList = new List<ManageBranchesDTO>();
                HttpResponseMessage AmenitiesRes = await client.PostAsJsonAsync("api/HotelAmenitiesAPI/NewGetHotelAmenity", aObj);
                if (AmenitiesRes.IsSuccessStatusCode)
                {
                    var AmenitiesData = AmenitiesRes.Content.ReadAsStringAsync().Result;
                    var AmenitiesList = JsonConvert.DeserializeObject<List<ManageHotelAmenitiesDTO>>(AmenitiesData);
                    a = AmenitiesList;
                    List<ManageHotelAmenitiesDTO> AmnList = AmenitiesList;
                    SelectList objModelData = new SelectList(AmnList, "Id", "NameAr", 0);
                    ViewBag.HotelAmenities = objModelData;
                }
                //HttpResponseMessage CountryRes = await client.PostAsJsonAsync("api/CountriesAPI/NewCountry", CountryObj);
                //if (CountryRes.IsSuccessStatusCode)
                //{
                //    var CountryData = CountryRes.Content.ReadAsStringAsync().Result;
                //    var ContryList = JsonConvert.DeserializeObject<List<ManageCountriesDTO>>(CountryData);
                //    SelectList ObjContData = new SelectList(ContryList, "Id", "NameAr", 0);
                //    ViewBag.CoutrList = ObjContData;
                //}

                HttpResponseMessage AmenRes = await client.PostAsJsonAsync("api/FindAHotelAPI/NewMapData", obj);
                if (AmenRes.IsSuccessStatusCode)
                {
                    var resData = AmenRes.Content.ReadAsStringAsync().Result;
                    var res = JsonConvert.DeserializeObject<ManageBranchesDTO>(resData);
                    var data = res.datasetXml;
                    if (data != null)
                    {
                        var document = new XmlDocument();
                        document.LoadXml(data);
                        DataSet ds = new DataSet();
                        ds.ReadXml(new XmlNodeReader(document));
                        if (ds.Tables.Count > 0)
                        {
                            if (ds.Tables[3].Rows.Count > 0)
                            {
                                CountriesList = ds.Tables[3].AsEnumerable().Select(dataRow => new ManageCountriesDTO
                                {
                                    Id = Convert.ToInt64(dataRow.Field<Int64>("CityId")),
                                    NameEn = dataRow.Field<string>("NameEn"),
                                    NameAr = dataRow.Field<string>("NameAr")
                                }).ToList();
                                    SelectList ObjContData = new SelectList(CountriesList, "Id", "NameAr", 0);
                                    ViewBag.CoutrList = ObjContData;
                                //TempData["CountriesList"] = CountriesList;
                            }
                            else
                            {
                                SelectList ObjContData = new SelectList("", "Id", "NameAr", 0);
                                ViewBag.CoutrList = ObjContData;
                            }
                            
                            if (ds.Tables[4].Rows.Count > 0)
                            {
                                var hotels = ds.Tables[4].AsEnumerable().Select(dataRow => new ManageHotelsDTO
                                {
                                    Id = Convert.ToInt64(dataRow.Field<Int64>("Id")),
                                    NameEn = dataRow.Field<string>("NameEn"),
                                    NameAr = dataRow.Field<string>("NameAr")
                                }).ToList();
                                SelectList ObjContData = new SelectList(hotels, "Id", "NameAr", 0);
                                ViewBag.BrandListMap = ObjContData;
                                //TempData["CountriesList"] = CountriesList;
                            }
                            else
                            {
                                SelectList ObjContData = new SelectList("", "Id", "NameAr", 0);
                                ViewBag.BrandListMap = ObjContData;
                            }
                            if (ds.Tables[4].Rows.Count > 0)
                            {
                               var hotels = ds.Tables[4].AsEnumerable().Select(dataRow => new ManageHotelsDTO
                                {
                                    Id = Convert.ToInt64(dataRow.Field<Int64>("Id")),
                                    NameEn = dataRow.Field<string>("NameEn"),
                                    NameAr = dataRow.Field<string>("NameAr")
                                }).ToList();
                                SelectList ObjContData = new SelectList(hotels, "Id", "NameAr", 0);
                                ViewBag.BrandList = ObjContData;
                                //TempData["CountriesList"] = CountriesList;
                            }
                            else
                            {
                                SelectList ObjContData = new SelectList("", "Id", "NameAr", 0);
                                ViewBag.BrandList = ObjContData;
                            }
                            if (TempData["htlId"] == null || TempData["AmtId"] == null)
                            {
                                if (ds.Tables[0].Rows.Count > 0)
                                {
                                    CountriesList = ds.Tables[0].AsEnumerable().Select(dataRow => new ManageCountriesDTO
                                    {
                                        Id = Convert.ToInt64(dataRow.Field<Int64>("CountryId")),
                                        NameEn = dataRow.Field<string>("NameEn"),
                                        NameAr = dataRow.Field<string>("NameAr")
                                    }).ToList();
                                    TempData["CountriesList"] = CountriesList;
                                }
                                else
                                {
                                    SelectList objmodeldata = new SelectList("", 0);
                                    ViewBag.cities = objmodeldata;
                                }
                                if (ds.Tables[1].Rows.Count > 0)
                                {
                                    Cityist = ds.Tables[1].AsEnumerable().Select(dataRow => new ManageCitiesDTO
                                    {
                                        Id = Convert.ToInt64(dataRow.Field<Int64>("CityId")),
                                        CountryId = Convert.ToInt64(dataRow.Field<Int64>("CountryId")),
                                        NameEn = dataRow.Field<string>("NameEn"),
                                        NameAr = dataRow.Field<string>("NameAr")
                                    }).ToList();
                                    TempData["Cityist"] = Cityist;
                                }
                                else
                                {
                                    SelectList objmodeldata = new SelectList("", 0);
                                    ViewBag.cities = objmodeldata;
                                }
                                if (ds.Tables[2].Rows.Count > 0)
                                {
                                    BranchList = ds.Tables[2].AsEnumerable().Select(dataRow => new ManageBranchesDTO
                                    {
                                        Id = Convert.ToInt64(dataRow.Field<Int64>("Id")),
                                        CityId = Convert.ToInt64(dataRow.Field<Int64>("cityId")),
                                        HotelId = Convert.ToInt64(dataRow.Field<Int64>("HotelId")),
                                        NameEn = dataRow.Field<string>("NameEn"),

BoudlGroup/Areas/ar/Views/FindAHotel/GetMapByAmenity.cshtml
@model BoudlGroup.FindAHotelDTO
@{
  Layout = null;
}
@*<script type="text/javascript" src="~/assets/js/jquery.js"></script>*@
<style>
     .mHeight {
            height: 700px;
        }
    </style>
<script>
   $(document).ready(function () {
       $("#hoteldetails").hide();
   });
   function hidediv()
   {
       $("#hoteldetails").hide();
   }
</script>

<div class="" id="hoteldetails" hidden>
        <div class="card" style="width: 18rem;">
            <div class="text-right"><i class="fa fa-times " style="cursor: pointer" onclick="return hidediv()"></i></div>
            <img id="imgmap" class="img-responsive" alt="Hotel Branch">
            <div class="card-body">
                <h5 class="card-title"><label class="text" id="mapdivtitle"></label></h5>
                @*<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>*@
                <a id="booklink" href="#" class="btn btn-primary" target="_blank">احجز الأن</a><br />
                <a id="weblink" href="#" class="book-now-btn" target="_blank">اعرض الفندق</a>

            </div>
        </div>
    </div>
<div class="loc-map mHeight" id="map">
</div>
<input type="hidden" value="" id="ZoomValue" />
<input type="hidden" value="@Model.Lat.Replace("(","")" id="txtlatitude" />
<input type="hidden" value="@Model.Lng.Replace(")","")" id="txtlongitude" />

@*@section scripts{*@

    <script type="text/javascript">
        $("body").addClass("internal-pages sticky trans-header contact type-1")
    </script>
<script type="text/javascript">
    var map;
    var markers = [];
    var markers1 = [];
    var gmarkers1 = [];
    var umarkers2 = [];
    var ugmarkers2 = [];
    var lastinfowindow;
    var locIndex = [];
    var data;
    var res;
    var HotelId = "";
    var AmenityId = "";
    var infowindow;
    //var url = "http://csadms.com/boudlgrouptest/Uploads/"
    var url = '@(Convert.ToString(System.Configuration.ConfigurationManager.AppSettings["imageurl"]))';
    var websiteurl = '@(Convert.ToString(System.Configuration.ConfigurationManager.AppSettings["hostFolder"]))';

    //$("#hoteldetails").hide();
    //$('#exploredata').hide();
    //$('#exploremap').show();
    //$('#Map1').click(function () {
    //    $('#exploredata').hide();
    //    $('#exploremap').show();
    //})
    //$('#Data1').click(function () {
    //    $('#exploredata').show();
    //    $('#exploremap').hide();
    //})


    //Credit: MDN

    //Credit: MDN
    if (!Array.prototype.forEach) {
        Array.prototype.forEach = function (fn, scope) {
            for (var i = 0, len = this.length; i < len; ++i) {
                fn.call(scope, this[i], i, this);
            }
        }
    }
    var array = [];

    function getIcon(type) {
        switch (type) {
            case 6: return "";
            case 7: return "http://boudl.com.com/assets/img/Boudl.png";
            case 8: return "http://brairahotels.com/test/assets/img/Braira.png";
            case 9: return "http://aberhotels.com/test/assets/img/Aber.png";
            case 10: return "http://www.narcissusriyadh.com/images/MapIcons/Narcissus.png";
            default: return "";
        }
    }
    function getsite(type) {
        switch (type) {
            //case 6: return "";
            //case 7: return "http://csadms.com/boudldev/ar/branches/";
            //case 8: return "http://csadms.com/brairadev/ar/branches/";
            //case 9: return "http://csadms.com/aberdev/ar/branches/";
            //case 10: return "http://csadms.com/boudlgroupdev/ar/branches/";

            case 7: return "http://boudl.com/ar/branches/";
            case 8: return "http://brairahotels.com/ar/branches/";
            case 9: return "http://aberhotels.com/ar/branches/";
            case 10: return "http://www.narcissusriyadh.com/ar";
            default: return "";
        }
    }
    var markerCluster;
    var lt = $("#txtlatitude").val();
    var lg = $("#txtlongitude").val();
    var tlat = lt == "0" ? 22.722470 :  lt;
    var tlng = lg == "0" ? 47.3357758 : lg;
    var tzoom = JSON.stringify(@Model.Zoom) == "0" ? 3 : JSON.stringify(@Model.Zoom);


    function initMap() {

        var mapOptions = {
            zoom: parseInt(tzoom),
            center: { lat: parseFloat(tlat), lng: parseFloat(tlng) },
            mapTypeId: google.maps.MapTypeId.TERRAIN,
            fullscreenControl: false,
            mapTypeControl: false
        };
        map = new google.maps.Map(document.getElementById('map'), mapOptions);
        infowindow = new google.maps.InfoWindow({
            content: ''
        });
        var temp="";
        debugger;
        if(@Model.Id == 1)
        {
            temp = JSON.stringify(@Model.AmenityIds);
        }
        else
        {
            temp = "";
        }
        $.ajax({
            url: '@Url.Action("getAmenities","FindAHotel")',
            type: "POST",
            dataType: "text json",
            data: { AmenitiesIDs: temp },
            //contentType: "application/json; charset=utf-8",
            success: function (result, status, jqXHR) {
                data = result;//data = JSON.stringify(result) ;
                markers1 = data;
                for (i = 0; i < markers1.length; i++) {
                    addMarker(markers1[i]);
                }
                //markerCluster = new MarkerClusterer(map, gmarkers1, {
                //    imagePath: 'https://cdn.rawgit.com/googlemaps/v3-utility-library/master/markerclustererplus/images/m'
                //});

                loadmpa(map, gmarkers1);
            },
            error: function (res) {
            }
        });
    }
    function loadmpa(_map, gmarkers1) {
        markerCluster = new MarkerClusterer(map, gmarkers1, {
            imagePath: 'https://cdn.rawgit.com/googlemaps/v3-utility-library/master/markerclustererplus/images/m'
        });
    }
    function addMarker(marker) {
        var category = marker.AmenityIds;
        var title = marker.BranchNameAr;
        var titleEn = marker.BranchNameEn;
        var pos = new google.maps.LatLng(parseFloat(marker.Lat), parseFloat(marker.Lng));
        var icons = getIcon(marker.HotelId);
        var BranchImage = marker.BranchImage;
        var link = marker.BookingURL;
        var hotelnameAr = marker.HotelNameAr;
        var hotelnameEn = marker.HotelNameEn;
        var hotel = marker.HotelId;


        var content = "";
        marker1 = new google.maps.Marker({
            title: title,
            titleEn: titleEn,
            position: pos,
            category: category,
            icon: icons,
            map: map,
            image: BranchImage,
            link: link,
            hotelNameEn :hotelnameEn,
            hotelNameAr :hotelnameAr,
            hotelid : hotel
        });

        gmarkers1.push(marker1);
        //Marker click listener
        google.maps.event.addListener(marker1, 'click', (function (marker1, content) {
            return function () {
                showdata(marker1);
            }
        })(marker1, content));

        google.maps.event.addListener(map, 'zoom_changed', function (event) {
            // alert('Lat: ' + event.latLng.lat() + ' and Longitude is: ' + event.latLng.lng());
            var a = map.getZoom();
            var ab = map.getMapTypeId();
            var abc = map.getCenter();
            $("#ZoomValue").val(a);
            $("#latitude").val(abc);

            var aaaa=map.getProjection;
            console.log($("#ZoomValue").val());
            console.log($("#latitude").val());




            //document.getElementById('ZoomValue').value =a.toString();
        });
        google.maps.event.addListener(marker, 'dragstart', function (event) {
            //alert('Lat: ' + event.latLng.data.Latitude() + ' and Longitude is: ' + event.latLng.data.Longitude());
            $("#latitude").val(event.latLng.data.Latitude());
            $("#longitude").val(event.latLng.data.Longitude());
            console.log($("#latitude").val());
            console.log($("#longitude").val());

        });

    }
    function showdata(marker1) {
        $("#hoteldetails").show();
        $("#imgmap").attr("src", url + marker1.image);
        $("#mapdivtitle").text(marker1.hotelNameAr +" "+ marker1.title);
        //$("#mapdivtitle").append(marker1.title);
        $("#booklink").attr("href", marker1.link);
        //$("#weblink").attr("href", "/ar/branches/"+ marker1.titleEn.replace(" ","-"));
        var hotel = getsite(marker1.hotelid)
        $("#weblink").attr("href", (hotel + marker1.titleEn.replace(' ','-')));

    }



</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDBdRx3UKvK7wCC1xx-pYVt_Wihfa41S1M&callback=initMap">
</script>

BoudlGroup/Areas/ar/Views/FindAHotel/GetMapData.cshtml
@model BoudlGroup.FindAHotelDTO
@{
    Layout = null;
}
@if (ViewBag.countries != null)
{
    foreach (var item in ViewBag.countries)
    {
        <h3>@item.NameAr</h3><hr />
        if (ViewBag.cities != null)
        {
            foreach (var citem in ViewBag.cities)
            {
                if (citem.CountryId == item.Id)
                {
                    <h5><strong>@citem.NameAr</strong></h5>
                    <br />
                    if (ViewBag.BranchList != null)
                    {
                        foreach (var bitem in ViewBag.BranchList)
                        {
                            if (bitem.CityId == citem.Id)
                            {
                                if (bitem.HotelId == 7)
                                {
                                    <a href="http://boudl.com/ar/branches/@bitem.NameEn.ToLower().Replace(" ", "-")" target="_blank"><span>@bitem.NameAr</span></a><br />
                                }
                                else if (bitem.HotelId == 8)
                                {
                                    <a href="http://brairahotels.com/ar/branches/@bitem.NameEn.ToLower().Replace(" ", "-")" target="_blank"><span>@bitem.NameAr</span></a><br />
                                }
                                else if (bitem.HotelId == 9)
                                {
                                    <a href="http://aberhotels.com/ar/branches/@bitem.NameEn.ToLower().Replace(" ", "-")" target="_blank"><span>@bitem.NameAr</span></a><br />
                                }
                                else if (bitem.HotelId == 10)
                                {
                                    <a href="http://www.narcissusriyadh.com/ar/" target="_blank"><span>@bitem.NameAr</span></a><br />
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}